AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda: payment-processor

  Process the client's payments

Parameters:
  FunctionName:
    Type: String
    Default: "payment-processor"
    Description: FunctionName inject params name conventions {repository-name}-{env} from workflows
  FunctionDescription:
    Type: String
    Default: >
      Process the client's payments
    Description: Function Description Show at lambda
  VersionDescription:
    Type: String
    Default: ""
    Description: Version Publish Description Show at lambda
  DataClassification:
    Type: String
    Default: "confidential"

Globals:
  Function:
    Timeout: 3

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Description: !Ref FunctionDescription
      CodeUri: ./src
      Handler: app.lambdaHandler
      PackageType: Zip
      Runtime: "nodejs22.x"
      VersionDescription: !Ref VersionDescription
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
  FunctionRoleArn:
    Description: "Implicit IAM Role created for Lambda function"
    Value: !GetAtt FunctionRole.Arn
